-- 1번

SELECT EMP_ID, EMP_NAME, PHONE, HIRE_DATE, DEPT_TITLE
FROM EMPLOYEE
NATURAL JOIN JOB
JOIN DEPARTMENT ON(DEPT_CODE = DEPT_ID)
WHERE (DEPT_CODE) = (SELECT DEPT_CODE
                                FROM EMPLOYEE
                                WHERE EMP_NAME = '전지연')
AND EMP_NAME != '전지연';



-- 2번
SELECT EMP_ID, EMP_NAME, PHONE, SALARY, JOB_NAME
FROM EMPLOYEE
JOIN JOB USING(JOB_CODE)
WHERE SALARY > ANY (SELECT SALARY
                    FROM EMPLOYEE
                    JOIN JOB USING(JOB_CODE)
                    WHERE JOB_NAME =(SELECT HIRE_DATE
                                     FROM EMPLOYEE
                                     WHERE EXTRACT(YEAR FROM HIRE_DATE) > 2000));
                                                
-- 3번
SELECT EMP_ID, EMP_NAME, DEPT_ID, JOB_CODE, DEPT_TITLE, JOB_NAME
FROM EMPLOYEE
NATURAL JOIN JOB
JOIN DEPARTMENT ON(DEPT_CODE = DEPT_ID)
WHERE (DEPT_CODE, JOB_CODE) = (SELECT DEPT_CODE, JOB_CODE
                                FROM EMPLOYEE
                                WHERE EMP_NAME = '노옹철')
AND EMP_NAME != '노옹철';              
               
-- 4번
SELECT EMP_ID, EMP_NAME, DEPT_CODE, JOB_CODE, HIRE_DATE
FROM EMPLOYEE
WHERE (DEPT_CODE, JOB_CODE) = (SELECT DEPT_CODE, JOB_CODE
                                FROM EMPLOYEE
                                WHERE EXTRACT(YEAR FROM HIRE_DATE) = 2000);                             


-- 5번
SELECT EMP_ID, EMP_NAME, DEPT_CODE, MANAGER_ID, EMP_NO, HIRE_DATE
FROM EMPLOYEE
WHERE (DEPT_CODE, MANAGER_ID)
    = (SELECT DEPT_CODE, MANAGER_ID
       FROM EMPLOYEE
       WHERE SUBSTR(EMP_NO, 8, 1) = '2'
       AND SUBSTR(EMP_NO, 1, 2) = '77');
      
      

-- 6번
SELECT EMP_ID, EMP_NAME,NVL(DEPT_TITLE, '소속없음'), JOB_NAME, HIRE_DATE, DEPT_CODE
FROM EMPLOYEE MAIN
LEFT JOIN DEPARTMENT ON (DEPT_CODE = DEPT_ID)
JOIN JOB USING (JOB_CODE)
WHERE (DEPT_CODE, HIRE_DATE) IN (SELECT DEPT_CODE, MIN(HIRE_DATE) FROM EMPLOYEE
                                 WHERE ENT_YN = 'N'
                                 GROUP BY DEPT_CODE)
                                 ORDER BY HIRE_DATE;      
      
      
-- 7번
SELECT EMP_ID, EMP_NAME, JOB_NAME,
ROUND(MONTHS_BETWEEN(SYSDATE,TO_DATE(SUBSTR(EMP_NO, 1, 6),'RRMMDD'))/12) "나이",
TO_CHAR((SALARY + (SALARY * NVL(BONUS, 0)))*12, 'L999,999,999')"보너스 포함 연봉"
FROM EMPLOYEE MAIN
JOIN JOB J ON (MAIN.JOB_CODE = J.JOB_CODE)
WHERE EMP_NO = (SELECT MAX(EMP_NO)
                FROM EMPLOYEE SUB
                WHERE MAIN.JOB_CODE = SUB.JOB_CODE)
ORDER BY 나이 DESC;


















